"""empty message

Revision ID: 27e52344f26f
Revises: 
Create Date: 2023-04-20 13:41:49.388505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e52344f26f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_enderecoUsuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.Column('numero', sa.String(length=9), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('senha', sa.String(length=30), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('observacoes', sa.String(length=700), nullable=True),
    sa.Column('EnderecoUsuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo_usuario', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['EnderecoUsuario_id'], ['tb_enderecoUsuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('senha')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_usuario')
    op.drop_table('tb_enderecoUsuario')
    # ### end Alembic commands ###
